org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neoforge_version=21.1.172
loader_version_range=[4,)

mapping_channel=official
mapping_version=1.21.1

mod_id=maid_rpg_task
mod_name=maid rpg task
mod_license=MIT
mod_version=1.3.3_a_1
mod_group_id=studio.fantasyit
mod_authors=xypp and Mateus
mod_description=Add some rpg task for touhou little maid.

geckolib_version=4.7.7
